### ISSUE TITLE
Usage with directories?

### ISSUE THREAD

**Issue by JamieMason** [fpascutti/glob-exec#1]
Thanks for this great tool @fpascutti, I wondered if you could help me? I'm wanting to loop over some directories and am having some trouble.

```
glob-exec foreach 'packages/*' -- 'echo {{file}}'
```

```
/bin/sh: packages/apollo-content: is a directory
/Users/jmn42/.nvm/versions/node/v8.11.1/lib/node_modules/glob-exec/lib/cli.js:55
    setImmediate(() => { throw reason; });
                         ^

Error: Command failed: packages/* echo {{file}}
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at executeSync (/Users/jmn42/.nvm/versions/node/v8.11.1/lib/node_modules/glob-exec/lib/cli.js:27:21)
    at <anonymous>
```

I think I probably can solve this using the `glob-options` mentioned in the readme? But I can't see an option which looks like it would do this.

Thank you for you time,

Jamie

**Comment by fpascutti** [comment]
Your command is missing double-dashes before the `foreach` argument.
It should be:
```sh
glob-exec --foreach 'packages/*' -- 'echo {{file}}'
```

Apart from that it worked well for me, listing files and directories from *packages* directory.

**Comment by JamieMason** [comment]
Ah, thanks a lot!
